/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

// MODELO PARA COMBOBOX COM FETCH
// <combobox> = new JComboBox();
// <combobox>.setModel(new DefaultComboBoxModel(<vetor_que_povoa>));
// <combobox>.setSelectedIndex(-1);
// <combobox>.setEditable(true);
// JTextField text = (JTextField)<combobox>.getEditor().getEditorComponent();
// text.setFocusable(true);
// text.setText("");
// text.addKeyListener(new ComboListener(<combobox>,<vetor_que_povoa>));
// <combobox>.setBounds(144, 56, 165, 24);
// contentPane.add(<combobox>);

package com.app;
import java.time.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author Victor
 */
public class _Graph extends javax.swing.JFrame {

    public ArrayList<Movie> movies = new ArrayList<Movie>();
    public Vector<Movie> vectorMovies = new Vector<Movie>();
    public Vector<Room> vectorRooms = new Vector<Room>();    
    public Vector<Session> vectorSessions = new Vector<Session>();
    public Vector<String> vectorCategory = new Vector<String>();
    public Vector<String> vectorClassification = new Vector<String>();
    
   

    /**
     * Creates new form _Graph
     */
    public _Graph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupType = new javax.swing.ButtonGroup();
        btnGroupMenu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbMenu = new javax.swing.JLabel();
        btnMovie = new javax.swing.JButton();
        btnRoom = new javax.swing.JButton();
        btnSession = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        rdCreate = new javax.swing.JRadioButton();
        rdEdit = new javax.swing.JRadioButton();
        rdSearch = new javax.swing.JRadioButton();
        tbPannel = new javax.swing.JTabbedPane();
        pnMovie = new javax.swing.JPanel();
        tbMovie_title = new javax.swing.JLabel();
        tbMovie_lbTitle = new javax.swing.JLabel();
        tbMovie_tfTitle = new javax.swing.JTextField();
        tbMovie_lbDirector = new javax.swing.JLabel();
        tbMovie_tfDirector = new javax.swing.JTextField();
        tbMovie_lbCategory = new javax.swing.JLabel();
        tbMovie_lbClassification = new javax.swing.JLabel();
        tbMovie_lbDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMovie_taDescription = new javax.swing.JTextArea();
        tbMovie_lbDuration = new javax.swing.JLabel();
        tbMovie_spDurHr = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        tbMovie_spDurationMin = new javax.swing.JSpinner();
        tbMovie_btnConfirm = new javax.swing.JButton();
        tbMovie_btnClear = new javax.swing.JButton();
        tbMovie_cbClassification = new javax.swing.JComboBox<>();
        tbMovie_cbcategory = new javax.swing.JComboBox<>();
        pmRoom = new javax.swing.JPanel();
        tbRoom_title = new javax.swing.JLabel();
        tbRoom_lbId = new javax.swing.JLabel();
        tbRoom_tfId = new javax.swing.JTextField();
        tbRoom_lbOcupation = new javax.swing.JLabel();
        tbRoom_spOcupation = new javax.swing.JSpinner();
        tbRoom_spPrice = new javax.swing.JSpinner();
        tbRoom_lbPrice = new javax.swing.JLabel();
        tbRoom_cbDefault = new javax.swing.JCheckBox();
        btnTypeContent = new javax.swing.JPanel();
        tbRoom_rdNormal = new javax.swing.JRadioButton();
        tbRoom_rd3D = new javax.swing.JRadioButton();
        tbRoom_lbTitle = new javax.swing.JLabel();
        tbRoom_btnConfirm = new javax.swing.JButton();
        tbRoom_btnClear = new javax.swing.JButton();
        pnSession = new javax.swing.JPanel();
        tbSession_title = new javax.swing.JLabel();
        lbSession_cbMovie = new javax.swing.JComboBox<>();
        tbSession_lbRoom = new javax.swing.JLabel();
        tbSession_cbRoom = new javax.swing.JComboBox<>();
        tbSession_lbMovie = new javax.swing.JLabel();
        tbSession_lbLotation = new javax.swing.JLabel();
        tbSession_spLotation = new javax.swing.JSpinner();
        tbSession_cbDefault = new javax.swing.JCheckBox();
        tbSession_lbTime = new javax.swing.JLabel();
        tbSession_cbDay = new javax.swing.JComboBox<>();
        tbSession_cbMounth = new javax.swing.JComboBox<>();
        tbSession_cbYear = new javax.swing.JComboBox<>();
        tbSession_btnConfirm = new javax.swing.JButton();
        tbSession_btnClear = new javax.swing.JButton();
        tbSession_lbtime = new javax.swing.JLabel();
        tbSession_cbHr = new javax.swing.JComboBox<>();
        tbSession_cbMin = new javax.swing.JComboBox<>();
        pnTicket = new javax.swing.JPanel();
        tbTicket_title = new javax.swing.JLabel();
        tbTicket_lbSession = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        tbTicket_lbName = new javax.swing.JLabel();
        tbTicket_tfName = new javax.swing.JTextField();
        tbTicket_lbAge = new javax.swing.JLabel();
        tbTicket_spAge = new javax.swing.JSpinner();
        tbTicket_cbStudy = new javax.swing.JCheckBox();
        btnConfirm = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tbTicket_tfCpf = new javax.swing.JTextField();
        tbTicket_lbCpf = new javax.swing.JLabel();
        tbTicket_lbPrice = new javax.swing.JLabel();
        tbTickect_tfPrice = new javax.swing.JTextField();
        
        // POVOAMENTO DE VETORES
        
	        // CATEGORIAS
	        vectorCategory.add("Ação");
	        vectorCategory.add("Aventura");
	        vectorCategory.add("Romance");
	        vectorCategory.add("Infantil");
	        vectorCategory.add("Animação");
	        vectorCategory.add("Terror");
	        
	        // CLASSIFICAÇÃO
	        vectorClassification.add("Livre");	        
	        vectorClassification.add("10 anos");
	        vectorClassification.add("12 anos");
	        vectorClassification.add("16 anos");
	        vectorClassification.add("18 anos");
	        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMenu.setText("Menu");

        btnMovie.setText("Add/Edit Movie");
        btnMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieActionPerformed(evt);
            }
        });

        btnRoom.setText("Add/Edit Room");
        btnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomActionPerformed(evt);
            }
        });

        btnSession.setText("Add/Edit Session");

        btnTicket.setText("Add/Edit Ticket");

        rdCreate.setText("Create");

        rdEdit.setText("Edit");

        rdSearch.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbMenu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdCreate)
                            .addComponent(rdEdit)
                            .addComponent(rdSearch)
                            .addComponent(btnRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMovie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTicket)
                .addGap(18, 18, 18)
                .addComponent(rdCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbMovie_title.setText("Movie");

        tbMovie_lbTitle.setText("Title");

        tbMovie_tfTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMovie_tfTitleActionPerformed(evt);
            }
        });

        tbMovie_lbDirector.setText("Director");

        tbMovie_tfDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMovie_tfDirectorActionPerformed(evt);
            }
        });

        tbMovie_lbCategory.setText("Category");

        tbMovie_lbClassification.setText("Classification");

        tbMovie_lbDescription.setText("Description");

        tbMovie_taDescription.setColumns(20);
        tbMovie_taDescription.setRows(5);
        jScrollPane1.setViewportView(tbMovie_taDescription);

        tbMovie_lbDuration.setText("Duration");

        jLabel9.setText(":");

        tbMovie_btnConfirm.setText("Confirm");
        tbMovie_btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMovie_btnConfirmActionPerformed(evt);
            }
        });

        tbMovie_btnClear.setText("Clear");
        tbMovie_btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMovie_btnClearActionPerformed(evt);
            }
        });

        tbMovie_cbClassification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbMovie_cbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tbMovie_cbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMovie_cbcategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMovieLayout = new javax.swing.GroupLayout(pnMovie);
        pnMovie.setLayout(pnMovieLayout);
        pnMovieLayout.setHorizontalGroup(
            pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMovieLayout.createSequentialGroup()
                .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMovieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbMovie_lbTitle)
                        .addGap(173, 173, 173)
                        .addComponent(tbMovie_lbDescription))
                    .addGroup(pnMovieLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(tbMovie_title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMovieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tbMovie_lbDirector)
                        .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbMovie_cbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbMovie_lbCategory)
                            .addComponent(tbMovie_tfDirector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tbMovie_tfTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tbMovie_lbClassification)
                    .addComponent(tbMovie_cbClassification, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(tbMovie_lbDuration)
                    .addGroup(pnMovieLayout.createSequentialGroup()
                        .addComponent(tbMovie_spDurHr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbMovie_spDurationMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMovieLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tbMovie_btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbMovie_btnConfirm)
                .addContainerGap())
        );
        pnMovieLayout.setVerticalGroup(
            pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMovieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbMovie_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbMovie_lbTitle)
                    .addComponent(tbMovie_lbDescription))
                .addGap(14, 14, 14)
                .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnMovieLayout.createSequentialGroup()
                        .addComponent(tbMovie_tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbMovie_lbDirector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbMovie_tfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbMovie_lbCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbMovie_cbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbMovie_lbDuration)
                    .addComponent(tbMovie_lbClassification))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbMovie_cbClassification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbMovie_spDurHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbMovie_spDurationMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(0, 93, Short.MAX_VALUE)
                .addGroup(pnMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbMovie_btnClear)
                    .addComponent(tbMovie_btnConfirm))
                .addContainerGap())
        );

        tbPannel.addTab("Movie", pnMovie);

        tbRoom_title.setText("Room");

        tbRoom_lbId.setText("ID");

        tbRoom_tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbRoom_tfIdActionPerformed(evt);
            }
        });

        tbRoom_lbOcupation.setText("Ocupation");

        tbRoom_lbPrice.setText("Price U$");

        tbRoom_cbDefault.setText("Default");

        btnTypeContent.setPreferredSize(new java.awt.Dimension(190, 100));

        tbRoom_rdNormal.setText("Normal");
        tbRoom_rdNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbRoom_rdNormalActionPerformed(evt);
            }
        });

        tbRoom_rd3D.setText("3D");

        javax.swing.GroupLayout btnTypeContentLayout = new javax.swing.GroupLayout(btnTypeContent);
        btnTypeContent.setLayout(btnTypeContentLayout);
        btnTypeContentLayout.setHorizontalGroup(
            btnTypeContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTypeContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnTypeContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbRoom_rdNormal)
                    .addComponent(tbRoom_rd3D))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        btnTypeContentLayout.setVerticalGroup(
            btnTypeContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTypeContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbRoom_rdNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbRoom_rd3D)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tbRoom_lbTitle.setText("Type");

        tbRoom_btnConfirm.setText("Confirm");

        tbRoom_btnClear.setText("Clear");

        javax.swing.GroupLayout pmRoomLayout = new javax.swing.GroupLayout(pmRoom);
        pmRoom.setLayout(pmRoomLayout);
        pmRoomLayout.setHorizontalGroup(
            pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmRoomLayout.createSequentialGroup()
                .addGroup(pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pmRoomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbRoom_tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pmRoomLayout.createSequentialGroup()
                                .addGroup(pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbRoom_spOcupation, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbRoom_lbOcupation))
                                .addGap(18, 18, 18)
                                .addGroup(pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbRoom_lbPrice)
                                    .addComponent(tbRoom_spPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbRoom_cbDefault))))
                        .addGap(22, 22, 22)
                        .addComponent(btnTypeContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pmRoomLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(tbRoom_title))
                    .addGroup(pmRoomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbRoom_lbId)
                        .addGap(185, 185, 185)
                        .addComponent(tbRoom_lbTitle)))
                .addGap(47, 98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmRoomLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tbRoom_btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbRoom_btnConfirm)
                .addContainerGap())
        );
        pmRoomLayout.setVerticalGroup(
            pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbRoom_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbRoom_lbId)
                    .addComponent(tbRoom_lbTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pmRoomLayout.createSequentialGroup()
                        .addComponent(tbRoom_tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbRoom_lbOcupation)
                            .addComponent(tbRoom_lbPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbRoom_spOcupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbRoom_spPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbRoom_cbDefault))
                    .addComponent(btnTypeContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(pmRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbRoom_btnConfirm)
                    .addComponent(tbRoom_btnClear))
                .addContainerGap())
        );

        tbPannel.addTab("Room", pmRoom);

        tbSession_title.setText("Session");

        lbSession_cbMovie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lbSession_cbMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSession_cbMovieActionPerformed(evt);
            }
        });

        tbSession_lbRoom.setText("Room");

        tbSession_cbRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tbSession_cbRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSession_cbRoomActionPerformed(evt);
            }
        });

        tbSession_lbMovie.setText("Movie");

        tbSession_lbLotation.setText("Lotation");

        tbSession_cbDefault.setText("Default");
        tbSession_cbDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSession_cbDefaultActionPerformed(evt);
            }
        });

        tbSession_lbTime.setText("Date");

        tbSession_cbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tbSession_cbDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSession_cbDayActionPerformed(evt);
            }
        });

        tbSession_cbMounth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbSession_cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbSession_btnConfirm.setText("jButton13");

        tbSession_btnClear.setText("jButton14");

        tbSession_lbtime.setText("Time");

        tbSession_cbHr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbSession_cbMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnSessionLayout = new javax.swing.GroupLayout(pnSession);
        pnSession.setLayout(pnSessionLayout);
        pnSessionLayout.setHorizontalGroup(
            pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSessionLayout.createSequentialGroup()
                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSessionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tbSession_btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbSession_btnConfirm))
                    .addGroup(pnSessionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnSessionLayout.createSequentialGroup()
                                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbSession_cbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbSession_lbMovie)
                                    .addComponent(lbSession_cbMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnSessionLayout.createSequentialGroup()
                                        .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tbSession_lbTime)
                                            .addComponent(tbSession_lbtime))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(pnSessionLayout.createSequentialGroup()
                                        .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tbSession_cbHr, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tbSession_spLotation, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tbSession_cbDay, javax.swing.GroupLayout.Alignment.LEADING, 0, 80, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnSessionLayout.createSequentialGroup()
                                                .addComponent(tbSession_cbDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(pnSessionLayout.createSequentialGroup()
                                                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tbSession_cbMin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(tbSession_cbMounth, 0, 90, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(tbSession_cbYear, 0, 77, Short.MAX_VALUE))))))
                            .addGroup(pnSessionLayout.createSequentialGroup()
                                .addComponent(tbSession_lbRoom)
                                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnSessionLayout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(tbSession_title))
                                    .addGroup(pnSessionLayout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addComponent(tbSession_lbLotation)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnSessionLayout.setVerticalGroup(
            pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSessionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbSession_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSession_lbLotation)
                    .addComponent(tbSession_lbRoom))
                .addGap(7, 7, 7)
                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSession_spLotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbSession_cbDefault)
                    .addComponent(tbSession_cbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSession_lbTime)
                    .addComponent(tbSession_lbMovie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSession_cbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbSession_cbMounth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbSession_cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSession_cbMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbSession_lbtime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSession_cbHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbSession_cbMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(pnSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSession_btnConfirm)
                    .addComponent(tbSession_btnClear))
                .addContainerGap())
        );

        tbPannel.addTab("Session", pnSession);

        tbTicket_title.setText("BuyPass");

        tbTicket_lbSession.setText("Session");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        tbTicket_lbName.setText("Name");

        tbTicket_tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTicket_tfNameActionPerformed(evt);
            }
        });

        tbTicket_lbAge.setText("Age");

        tbTicket_cbStudy.setText("I'm Study");
        tbTicket_cbStudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTicket_cbStudyActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");

        btnClear.setText("Clear");

        tbTicket_lbCpf.setText("CPF");

        tbTicket_lbPrice.setText("Price (U$)");

        tbTickect_tfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTickect_tfPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTicketLayout = new javax.swing.GroupLayout(pnTicket);
        pnTicket.setLayout(pnTicketLayout);
        pnTicketLayout.setHorizontalGroup(
            pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTicketLayout.createSequentialGroup()
                .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTicketLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear))
                    .addGroup(pnTicketLayout.createSequentialGroup()
                        .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbTicket_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnTicketLayout.createSequentialGroup()
                                    .addGap(188, 188, 188)
                                    .addComponent(tbTicket_title))
                                .addGroup(pnTicketLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(tbTicket_lbSession))
                                .addGroup(pnTicketLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(tbTicket_lbName))
                                .addGroup(pnTicketLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnTicketLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(tbTicket_lbAge))
                                .addGroup(pnTicketLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(tbTicket_spAge, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tbTicket_cbStudy))
                                .addGroup(pnTicketLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tbTicket_lbCpf)
                                        .addComponent(tbTicket_tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTicketLayout.createSequentialGroup()
                                .addComponent(tbTicket_lbPrice)
                                .addGap(0, 56, Short.MAX_VALUE))
                            .addComponent(tbTickect_tfPrice))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm)
                .addContainerGap())
        );
        pnTicketLayout.setVerticalGroup(
            pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbTicket_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTicket_lbSession)
                    .addComponent(tbTicket_lbPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbTickect_tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbTicket_lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbTicket_tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbTicket_lbAge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTicket_spAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbTicket_cbStudy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbTicket_lbCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbTicket_tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(pnTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        tbPannel.addTab("Ticket", pnTicket);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbPannel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tbPannel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }                                          

    private void btnMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieActionPerformed
        // TODO add your handling code here:
        tbPannel.setSelectedComponent(pnMovie);
    }//GEN-LAST:event_btnMovieActionPerformed

    private void btnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRoomActionPerformed

    private void tbTickect_tfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTickect_tfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTickect_tfPriceActionPerformed

    private void tbTicket_cbStudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTicket_cbStudyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTicket_cbStudyActionPerformed

    private void tbTicket_tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTicket_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTicket_tfNameActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void tbSession_cbDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSession_cbDayActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tbSession_cbDayActionPerformed

    private void tbSession_cbDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSession_cbDefaultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSession_cbDefaultActionPerformed

    private void tbSession_cbRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSession_cbRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSession_cbRoomActionPerformed

    private void lbSession_cbMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSession_cbMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSession_cbMovieActionPerformed

    private void tbRoom_rdNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbRoom_rdNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRoom_rdNormalActionPerformed

    private void tbRoom_tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbRoom_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRoom_tfIdActionPerformed

    private void tbMovie_cbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMovie_cbcategoryActionPerformed
        // TODO add your handling code here:
        Movie m = new Movie(LocalTime.parse("02:00"), "teste", "Teste", "teste", "teste");
        System.out.println(tbMovie_cbcategory.getSelectedItem().equals(m));
    }//GEN-LAST:event_tbMovie_cbcategoryActionPerformed

    private void tbMovie_btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMovie_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMovie_btnClearActionPerformed

    private void tbMovie_btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMovie_btnConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMovie_btnConfirmActionPerformed

    private void tbMovie_tfDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMovie_tfDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMovie_tfDirectorActionPerformed

    private void tbMovie_tfTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMovie_tfTitleActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tbMovie_tfTitleActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirm;
    private javax.swing.ButtonGroup btnGroupMenu;
    private javax.swing.ButtonGroup btnGroupType;
    private javax.swing.JButton btnMovie;
    private javax.swing.JButton btnRoom;
    private javax.swing.JButton btnSession;
    private javax.swing.JButton btnTicket;
    private javax.swing.JPanel btnTypeContent;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JComboBox<String> lbSession_cbMovie;
    private javax.swing.JPanel pmRoom;
    private javax.swing.JPanel pnMovie;
    private javax.swing.JPanel pnSession;
    private javax.swing.JPanel pnTicket;
    private javax.swing.JRadioButton rdCreate;
    private javax.swing.JRadioButton rdEdit;
    private javax.swing.JRadioButton rdSearch;
    private javax.swing.JButton tbMovie_btnClear;
    private javax.swing.JButton tbMovie_btnConfirm;
    private javax.swing.JComboBox<String> tbMovie_cbClassification;
    private javax.swing.JComboBox<String> tbMovie_cbcategory;
    private javax.swing.JLabel tbMovie_lbCategory;
    private javax.swing.JLabel tbMovie_lbClassification;
    private javax.swing.JLabel tbMovie_lbDescription;
    private javax.swing.JLabel tbMovie_lbDirector;
    private javax.swing.JLabel tbMovie_lbDuration;
    private javax.swing.JLabel tbMovie_lbTitle;
    private javax.swing.JSpinner tbMovie_spDurHr;
    private javax.swing.JSpinner tbMovie_spDurationMin;
    private javax.swing.JTextArea tbMovie_taDescription;
    private javax.swing.JTextField tbMovie_tfDirector;
    private javax.swing.JTextField tbMovie_tfTitle;
    private javax.swing.JLabel tbMovie_title;
    private javax.swing.JTabbedPane tbPannel;
    private javax.swing.JButton tbRoom_btnClear;
    private javax.swing.JButton tbRoom_btnConfirm;
    private javax.swing.JCheckBox tbRoom_cbDefault;
    private javax.swing.JLabel tbRoom_lbId;
    private javax.swing.JLabel tbRoom_lbOcupation;
    private javax.swing.JLabel tbRoom_lbPrice;
    private javax.swing.JLabel tbRoom_lbTitle;
    private javax.swing.JRadioButton tbRoom_rd3D;
    private javax.swing.JRadioButton tbRoom_rdNormal;
    private javax.swing.JSpinner tbRoom_spOcupation;
    private javax.swing.JSpinner tbRoom_spPrice;
    private javax.swing.JTextField tbRoom_tfId;
    private javax.swing.JLabel tbRoom_title;
    private javax.swing.JButton tbSession_btnClear;
    private javax.swing.JButton tbSession_btnConfirm;
    private javax.swing.JComboBox<String> tbSession_cbDay;
    private javax.swing.JCheckBox tbSession_cbDefault;
    private javax.swing.JComboBox<String> tbSession_cbHr;
    private javax.swing.JComboBox<String> tbSession_cbMin;
    private javax.swing.JComboBox<String> tbSession_cbMounth;
    private javax.swing.JComboBox<String> tbSession_cbRoom;
    private javax.swing.JComboBox<String> tbSession_cbYear;
    private javax.swing.JLabel tbSession_lbLotation;
    private javax.swing.JLabel tbSession_lbMovie;
    private javax.swing.JLabel tbSession_lbRoom;
    private javax.swing.JLabel tbSession_lbTime;
    private javax.swing.JLabel tbSession_lbtime;
    private javax.swing.JSpinner tbSession_spLotation;
    private javax.swing.JLabel tbSession_title;
    private javax.swing.JTextField tbTickect_tfPrice;
    private javax.swing.JCheckBox tbTicket_cbStudy;
    private javax.swing.JLabel tbTicket_lbAge;
    private javax.swing.JLabel tbTicket_lbCpf;
    private javax.swing.JLabel tbTicket_lbName;
    private javax.swing.JLabel tbTicket_lbPrice;
    private javax.swing.JLabel tbTicket_lbSession;
    private javax.swing.JSpinner tbTicket_spAge;
    private javax.swing.JTextField tbTicket_tfCpf;
    private javax.swing.JTextField tbTicket_tfName;
    private javax.swing.JLabel tbTicket_title;
    // End of variables declaration//GEN-END:variables
}
